baseURL = 'https://magixsource.github.io/'
languageCode = 'en-us'
title = 'X开源'
theme = "docsy"
prettyurls=true


[menu]
[[menu.main]]
   name = "Home"
   url  = "/"
   weight = 1
   pre = "<i class='fa-solid fa-home'></i>"
    
[[params.versions]]
	version = "master"
	url = "https://latest.localhost"

[[params.versions]]
	version = "v0.2"
	url = "https://v0-2.localhost"

[[params.versions]]
	version = "v0.3"
	url = "https://v0-3.localhost"



[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "User mailing list"
	url = "https://example.org/mail"
	icon = "fa fa-envelope"
        desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="Twitter"
	url = "https://example.org/twitter"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "Stack Overflow"
	url = "https://example.org/stack"
	icon = "fab fa-stack-overflow"
        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/google/docsy"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://example.org/slack"
	icon = "fab fa-slack"
        desc = "Chat with other project developers"
[[params.links.developer]]
	name = "Developer mailing list"
	url = "https://example.org/mail"
	icon = "fa fa-envelope"
        desc = "Discuss development issues around the project"

[params]
	version_menu = "Release"
	version = "0.1"
	archived_version = true
	offlineSearch = true
	offlineSearchMaxResults = 25
	url_latest_version = "https://your-latest-doc-site.com"
	# ui.sidebar_menu_compact = true
	ui.sidebar_menu_foldable = true
	ui.sidebar_search_disable = true
	ui.readingtime.enable = false
	# Format dates with Go's time formatting
  date_format = "2006-01-02"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5